### ISSUE TITLE
Seems not to work on Windows

### ISSUE THREAD

**Issue by leecommamichael** [thetarnav/odin-wasm#1]
<img width="405" alt="image" src="https://github.com/thetarnav/odin-wasm/assets/13748676/e4fba393-d805-4e67-9a50-41d049df10c8">

I pulled Odin from master this evening and built the compiler, this is the outcome of `npm run preview`

**Comment by thetarnav** [comment]
hey
are you using llvm 14, or other version?
because this looks like https://github.com/odin-lang/Odin/issues/2855

**Comment by thetarnav** [comment]
The issue with llvm 17 seems to be fixed so I hope that the project can be used on windows :)
